name: First WorkFlow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on:macos-11
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo: "Done"
      
